// src/core/components/options/options.tsx
import { FC } from 'react'
import styles from './options.module.scss'
import { bind } from '../../utils/bind'
import { Theme } from '../../../features/blog/application/state/theme'
import { Locale } from '../../../features/blog/domain/language/locale'

const cx = bind(styles)

export const Options: FC = () => {
  const themes = [
    { text: 'light', value: Theme.LIGHT },
    { text: 'dark', value: Theme.DARK },
  ]

  const locales = [
    { text: 'en', value: Locale.EN },
    { text: 'es', value: Locale.ES },
  ]
  return (
    <div className={cx('options')}>
      <select>
        {themes.map(x => (
          <option key={x.value} value={x.value}>
            {x.text}
          </option>
        ))}
      </select>
      <select>
        {locales.map(x => (
          <option key={x.value} value={x.value}>
            {x.text}
          </option>
        ))}
      </select>
    </div>
  )
}

// src/ui/commons/Options.vue
<template>
  <div>
    <label>
      {{ languageLabel }}
      <select v-model="locale" @change="changeLocale(locale)">
        <option v-for="locale in locales" :key="locale.value" :value="locale.value">{{
          locale.text
        }}</option>
      </select>
    </label>
    <label>
      {{ themeLabel }}
      <select v-model="theme" @change="changeTheme(theme)">
        <option v-for="theme in themes" :key="theme.value" :value="theme.value">{{
          theme.text
        }}</option>
      </select>
    </label>
  </div>
</template>

<script lang="ts">
import { Component, Inject, Vue } from 'vue-property-decorator'
import { Theme } from '../theme/Theme'
import { Locale } from '../../domain/language'
import { Translate } from './Translate'
import { State } from '../../application/state'

@Component
export default class Options extends Vue {
  @Inject()
  readonly translate!: Translate

  @Inject()
  readonly state!: State

  theme = Theme.DEFAULT
  themes = [{ text: this.light, value: Theme.LIGHT }, { text: this.dark, value: Theme.DARK }]

  locale = Locale.DEFAULT
  locales = [{ text: this.en, value: Locale.EN }, { text: this.es, value: Locale.ES }]

  get en() {
    return this.translate('_en')
  }

  get es() {
    return this.translate('_es')
  }

  get light() {
    return this.translate('_light')
  }

  get dark() {
    return this.translate('_dark')
  }

  get themeLabel() {
    return this.translate('_theme')
  }

  get languageLabel() {
    return this.translate('_language')
  }

  changeLocale(locale: Locale) {
    this.state.locale = locale
  }

  changeTheme(theme: Theme) {
    this.state.theme = theme
  }
}
</script>
<style scoped>
label {
  margin-right: var(--small-size);
}

select {
  background: transparent;
  color: var(--primary-color);
  border-color: var(--primary-color);
}
</style>
