// src/ui/commons/ArticleExcerpt.vue
<template>
  <div>
    <h3>{{ excerpt.title }}</h3>
    <span class="slugline">{{ excerpt.date }}</span>
    <p>{{ excerpt.body }}</p>
  </div>
</template>

<script lang="ts">
import { Component, Prop, Vue } from 'vue-property-decorator'
import { Article } from '../../domain/articles/Article'

@Component
export default class ArticleExcerpt extends Vue {
  @Prop()
  excerpt!: ReturnType<Article['getExcerpt']>
}
</script>

<style scoped>
.slugline {
  font-size: calc(var(--body-size) - 2);
  color: var(--gray-color);
}
</style>

// src/features/home/ui/article-excerpt.tsx
import type { FC } from 'react'
import type { Article } from '../../articles/domain/article'
import { Link } from '../../../core/components/link/link'
import { Markdown } from '../../../core/components/markdown/markdown'
import { useTranslations } from 'next-intl'

export const ArticleExcerpt: FC<{ excerpt: ReturnType<Article['getExcerpt']> }> = ({ excerpt }) => {
  const t = useTranslations()
  return (
    <Link to={`articles/${excerpt.id.value}`} type={'invisible'}>
      <article className={'excerpt'}>
        <h3 className={'title'} dangerouslySetInnerHTML={{ __html: excerpt.title }}></h3>
        <div className={'slugline'}>
          <span>{excerpt.date}</span>
          <span className={'accented-slugline'}>
            {' '}
            <strong>/</strong>{' '}
          </span>
          <span>
            {excerpt.readingTime.minutes} {t('article.minutes')}
          </span>
        </div>
        <Markdown value={excerpt.body} />
      </article>
    </Link>
  )
}
